### ISSUE TITLE
Docker compose components are unable to connect with each other

### ISSUE THREAD

**Issue by psengupta1973** [eiffel-community/eiffel-easy2use#61]
### Description

A configuration guide is helpful

### Motivation

This is actually a roadblock for integration
### Exemplification

To setup and run the docker compose sandbox, I have spent a nearly a week but unable make out the root cause.
### Benefits

Initial installation and configuration should be easy.

### Possible Drawbacks

Here is the exception
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to remrem_generate:8095 [remrem_generate/172.18.0.7] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.ericsson.eiffel.common.rest.RESTHttpClient.getPostRequestResponse(RESTHttpClient.java:130)
        at com.ericsson.eiffel.common.rest.RESTHttpClient.postRequest(RESTHttpClient.java:102)
        at com.ericsson.eiffel.common.rest.RemremGenerateClient.generateEiffelMessage(RemremGenerateClient.java:132)
        ... 95 more
C

**Comment by m-linner-ericsson** [comment]
Hi, could you please provide the commands you used to run this and attach the log from this run?

**Comment by m-linner-ericsson** [comment]
@psengupta1973 Do you have any more comments or is it ok if we close it?

**Comment by m-linner-ericsson** [comment]
Since no replies have come in and we don't know how to recreate the issue we will close this.
